all:
	# This is a svg with javascript DOM manipulation
	# Open the .svg file with your favorite browser
	# `$ make run' if you're really lazy
	# 
	# Try it with a fast javascript renderer (webkit)

run:
	x-www-browser bam.svg

