all:
	# This is a svg with javascript DOM manipulation
	# Open the .svg file with your favorite browser
	# `$ make run' is you're really lazy"
	# 
	# also, this is kind of slow. Try using webkit...

run:
	x-www-browser bam.svg

